### ISSUE TITLE
The db or persistent data need to be separated

### ISSUE THREAD

**Issue by joanhey** [chesslablab/chess-server#351]
It's the same if the user ask via API or via Websocket.
If the classes than need the db are separated, work with anything !!

With API, Websockets, ...

**Comment by joanhey** [comment]
Sorry, you close #358
And it's a break to 2 more issues !!

**Comment by programarivm** [comment]
The data command container in [src/Command/Data/CommandContainer.php](https://github.com/chesslablab/chess-server/blob/main/src/Command/Data/CommandContainer.php) is now responsible for instantiating the database connection on startup. 

See https://github.com/chesslablab/chess-server/issues/354#issuecomment-2293179065

Can you be a little more specific and describe what is broken because of the update?

Keep it up,
