### ISSUE TITLE
❓ Use `amphp/parallel` for async task

### ISSUE THREAD

**Issue by ging-dev** [chesslablab/chess-server#422]
Starting from `workerman` v5, it will support the Revolt event loop and be compatible with `amphp` v3.

**Comment by programarivm** [comment]
Thank you @ging-dev for opening this issue!

At the moment AMPHP can't be installed because of a compatibility issue with Rubix ML.

See:

- https://github.com/amphp/parallel/issues/206

The Spatie async library providing a wrapper around PHP's PCNTL extension is used in order for asynchronous commands to not block the event loop.
